### ISSUE TITLE
Is there a way to hide the 'badge' that displays the length?

### ISSUE THREAD

**Issue by tcarolan** [calipho-sib/sequence-viewer#1]
Is there a way to hide the 'badge' that displays the length?

**Comment by MatSchaeff** [comment]
Hi Tom,

I just added a display option **badge** to allow you to hide the badge.
Checkout the updated documentation : 
http://rawgit.com/calipho-sib/sequence-viewer/master/examples/index.html

Thank you for your suggestion and feel free to contact us again !

Cheers,

Mathieu

**Comment by tcarolan** [comment]
Wow! Thanks for implementing it. The viewer is great, simple to use and
just what I needed.

-Tom

On Tue, Nov 24, 2015 at 7:08 AM, Mathieu Schaeffer <notifications@github.com

**Comment by MatSchaeff** [comment]
Hi Tom,

Thank you for your appreciation, we are glad to hear it !

If you want, you can add a small reference to nextprot (www.nextprot.org) on your website if you have one :)
(link to logo : https://search.nextprot.org/img/np.png )

Cheers,

Mathieu
