### ISSUE TITLE
examples link broken

### ISSUE THREAD

**Issue by piotr-gawron** [calipho-sib/sequence-viewer#11]
The link in Examples sections (https://www.nextprot.org/entry/NX_P01308/view/proteomics) is broken. The result site returns an error:
"Oooops an error occured
Send Report"

**Comment by neXtProt** [comment]
Hello Piotr,

You should use the new URL:
https://www.nextprot.org/entry/NX_P01308/proteomics

Sorry that the old one doesn't redirects you automatically to the new address.
Thanks for your interest in neXtProt
The CALIPHO team


Pierre-André Michel
SIB | Swiss Institute of Bioinformatics
CMU - 1, rue Michel Servet - 1211 Geneva 4
Pierre-Andre.Michel@sib.swiss
http://www.sib.swiss

**Comment by piotr-gawron** [comment]
sure I can use it, but it's on the main page of the project in the examples section, so maybe you could change it to the correct one?

**Comment by ddtxra** [comment]
Thanks for your suggestion @piotr-gawron 
I have updated the documentation for this URL: https://search.nextprot.org/entry/NX_P01308/structures
